---
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
#  namespace: monitoring
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
#  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:9da595ecbb733074a1d3c6091a1e0c384da4f4e1f19f4e16276062278da8e592
        ports:
        - containerPort: 8080
        env:
        - name: ZK_HOSTS
          value: zookeeper.default:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=8080
