apiVersion: v1
kind: Service
metadata:
  name: kibana
#  namespace: monitoring
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kibana
#  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.8.10
        env:
        - name: TEST-FIELD
          value: TEST-VALUE
        volumeMounts:
        - name: configmap
          mountPath: /etc/kibana-config
#        - name: configmap
#          mountPath: /usr/share/kibana/config/kibana.yml
#          subPath: kibana.yml
      volumes:
      - name: configmap
        configMap:
          name: kibana-config

