apiVersion: v1
kind: Service
metadata:
  name: elastic-manager
#  namespace: monitoring
spec:
  ports:
  - port: 80
  selector:
    app: elastic-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-manager
#  namespace: monitoring
  labels:
    app: elastic-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-manager
  template:
    metadata:
      labels:
        app: elastic-manager
    spec:
      containers:
      - name: nginx
        image: dev.pcr.kr/plab/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap
          mountPath: /etc/nginx-config
        - name: configmap
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: configmap
        configMap:
          name: elastic-manager-config


